######################################################################
# Automatically generated by qmake (3.0) ? 1 27 00:53:23 2017
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += ../src/solve.h
SOURCES += test.cpp ../src/solve.cpp
