######################################################################
# Automatically generated by qmake (3.0) ? 1 12 11:25:49 2017
######################################################################

TEMPLATE = app
TARGET = test16
INCLUDEPATH += .
QT += testlib

# Input
HEADERS += ../../src/1_6/solve.h
SOURCES += test16.cpp ../../src/1_6/solve.cpp
